name: .NET

on:
  push:
    branches: [ plw_overhaul ]
  pull_request:
    branches: [ plw_overhaul ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: use this action, test solution dir
      uses: zyborg/dotnet-tests-report@v1
      with:
          project_path: CSProlog.Core.Test
          report_name: my_project_tests
          report_title: My Project Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
