name: dotNet

on:
  push:
    branches: [ plw_overhaul ]
  pull_request:
    branches: [ plw_overhaul ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Unit tests CSharpProlog
      uses: zyborg/dotnet-tests-report@v1
      with:
        skip_check_run: true
        project_path: CSProlog.Core.Test
        report_name: csharpprolog_tests
        report_title: CSharpProlog Tests
        github_token: ${{ secrets.GITHUB_TOKEN }}
        gist_name: csharpprolog_tests.md
        gist_badge_label: 'CSharpProlog Tests: %Counters_passed%/%Counters_total%'
        gist_token: ${{ secrets.GIST_TOKEN }}
        trx_xsl_path: trx2md.xsl
